---
title: "Bass Model HW"
author: "Yeva Avetisyan"
date: "2023-09-29"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(lubridate)
library(rlang)
library(ggplot2)
library(forecast)
library(readxl)
library(lmtest)
library(readr)
library(tidyverse)
library(tseries)
library(readxl)
library(ggpubr)
```

# Reading the datasets

```{r}
sales <- read_excel("C:/Users/User/Desktop/sales.xlsx", sheet = "Data")
usage <- read_excel("C:/Users/User/Desktop/usage.xlsx", sheet = "Data")
```
# Making some adjustments on the datasets to match the goal.

```{r}
sales <- sales[-c(1, 2), ]
usage <- usage[-c(1, 2), ]
usage <- usage[, -ncol(usage)]

column_names_sales <- c("Year", "Unit_Sales_in_millions")
column_names_usage <- c("Location", "Wireless_earbuds_in_%", "Wireless_headphones_in_%")

colnames(sales) <- column_names_sales
colnames(usage) <- column_names_usage

sales$Year[2] <- "2019"
sales$Year <- as.integer(sales$Year)
sales$Unit_Sales_in_millions <- as.integer(sales$Unit_Sales_in_millions)
usage$`Wireless_earbuds_in_%` <- as.integer(usage$`Wireless_earbuds_in_%`)
usage$`Wireless_headphones_in_%` <- as.integer(usage$`Wireless_headphones_in_%`)
```

# Visualizing the sales and usage of regular headphones/earbuds

```{r}
ggplot(sales, aes(x = Year, y = Unit_Sales_in_millions)) + geom_bar(stat = "identity", fill = '#F0BB40') +
  labs(x = " ", y = "Unit Sales in millions") +
  ggtitle("Global sales volume for true wireless hearables") +
  scale_x_continuous(breaks = 2018:2021, labels = 2018:2021) + theme_bw()
```

```{r}
ggplot(usage, aes(x = `Wireless_earbuds_in_%`, y = Location)) + geom_bar(stat = "identity", fill = "#AF5AB9") +
  labs(x = "Wireless earbuds in %", y = " ", title = "Global wireless earbuds usage in 2020") + theme_bw()
```

# Bass Model parameters for regular headphones/earbuds.

```{r}
bass.f <- function(t,p,q){((p+q)^2/p)*exp(-(p+q)*t)/(1+(q/p)*exp(-(p+q)*t))^2}
bass.F <- function(t,p,q){(1-exp(-(p+q)*t))/(1+(q/p)*exp(-(p+q)*t))}

# innovation rate = p
# imitation rate = q
```

# Model summary, parameter estimation

```{r}
salesbass = sales$Unit_Sales_in_millions
t = 1:length(salesbass)
bassM = nls(salesbass ~ m*(((p+q)^2/p)*exp(-(p+q)*t))/(1+(q/p)*exp(-(p+q)*t))^2, start = c(list(m=sum(salesbass), p=0.02, q=0.4)))
summary(bassM)
```

# Innovation rate (p = 0.01569)
# Imitation rate (q = 1.046)
# Market potential (m = 1110)


```{r}
df <- data.frame(t = c(1:9))

plot_of_t = ggplot(df, aes(t)) + stat_function(fun = bass.f, args = c(p = 0.01569, q = 1.046)) + ggtitle("Plot of f(t)") + theme_bw()

sales_plot = ggplot(sales, aes(x = Year, y = Unit_Sales_in_millions)) + geom_bar(stat = "identity") +
  labs(x = " ", y = "Unit Sales in millions") +
  ggtitle("Global sales volume") +
  scale_x_continuous(breaks = 2018:2021, labels = 2018:2021) + theme_bw()

ggarrange(plot_of_t, sales_plot)
```

# Estimated number of adopters by time

```{r}
sales$predicted_sales = bass.f(1:4, p = 0.01569, q = 1.046)*1110

ggplot(sales, aes(x = Year, y = Unit_Sales_in_millions)) + geom_bar(stat = 'identity', fill = "#F0BB40") +
  geom_point(mapping = aes(x=Year, y=predicted_sales), color = 'red') +
  labs( x= ' ', y = 'Sales', title = "Estimated number of adopters by time") + scale_x_continuous(breaks = 2018:2021, labels = 2018:2021) + theme_bw()
```

